project_name: kubecd
builds:
  - id: kcd
    main: ./cmd/kcd
    binary: kcd
    hooks:
      pre: go mod download
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
    env:
      - CGO_ENABLED=0
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - kcd
    image_templates:
      - "zedge/kubecd:latest"
      - "zedge/kubecd:{{ .Version }}"
      - "zedge/kubecd:{{ .Major }}.{{ .Minor }}"
      - "zedge/kubecd:{{ .Major }}"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
    skip_push: false
    dockerfile: Dockerfile
archives:
  - id: default
    format: tar.gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^build:'
    - '^WiP'
    - '^housekeeping:'
    - '^CI:'
release:
  github:
    owner: zedge
    name: kubecd
  draft: false
  disable: false
brews:
  - github:
      owner: kubecd
      name: homebrew-kubecd
    commit_author:
      name: goreleaserbot
      email: kubecd@stigbakken.com
    folder: Formula
    homepage: "https://github.com/zedge/kubecd/"
    description: "Kubernetes GitOps deployment tool"
    dependencies:
      - kubernetes-cli
      - kubernetes-helm
    test: |
      system "#{bin}/kcd version"
    install:
      bin.install "kcd"
nfpms:
  - builds:
      - kcd
    homepage: https://github.com/zedge/kubecd/
    maintainer: Stig Bakken <stig@stigbakken.com>
    description: "Kubernetes GitOps deployment tool"
    license: Apache 2.0
    formats:
      - deb
      - rpm
