project_name: kubecd
builds:
  - id: default
    main: ./cmd/kcd
    binary: kcd
    hooks:
      pre: go mod download
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    format: tar.gz
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^build:'
    - '^WiP'
    - '^housekeeping:'
    - '^CI:'
release:
  github:
    owner: zedge
    name: kubecd
  draft: true
  disable: false
