sudo: required
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - make
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - pytest
  - flake8
