sudo: required
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - make
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - pytest
  - flake8
  - docker build -t zedge/kubecd:latest .
deploy:
  - provider: script
    script: docker push zedge/kubecd:latest
    on:
      branch: master
      python: '3.5'
