#name: goreleaser
#
#on:
#  push:
#    tags:
#      - v*
#
#jobs:
#  goreleaser:
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v1
#      -
#        name: Set up Go
#        uses: actions/setup-go@v1
#        with:
#          go-version: "1.13"
#      -
#        name: Docker Login
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: |
#          docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
#      -
#        name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v1
#        with:
#          version: latest
#          args: release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

